##############################################################################
# Copyright (c) Lawrence Livermore National Security, LLC and other Merlin
# Project developers. See top-level LICENSE and COPYRIGHT files for dates and
# other details. No copyright assignment is required to contribute to Merlin.
##############################################################################

"""
Merlin local script adapter for executing workflow steps in worker environments.

This module provides the `MerlinLocalScriptAdapter` class, which extends Maestro's
`LocalScriptAdapter` to integrate with Merlin's worker-based execution system.
The adapter generates simple shell scripts and executes them locally within
Celery workers, applying Merlin-specific return code handling and step management.

The adapter is designed for workflow steps that don't require scheduler-specific
features and can run directly in the worker environment with basic shell execution.
"""

import logging

from maestrowf.interfaces.script.localscriptadapter import LocalScriptAdapter

from merlin.script_adapters.submission_mixin import MerlinSubmissionMixin


LOG = logging.getLogger(__name__)


class MerlinLocalScriptAdapter(MerlinSubmissionMixin, LocalScriptAdapter):
    """
    Script adapter for local execution of workflow steps in Merlin workers.

    This adapter combines Maestro's `LocalScriptAdapter` script generation capabilities
    with Merlin's worker-based execution system through the `MerlinSubmissionMixin`.
    It generates simple shell scripts without scheduler directives and executes them
    locally within Celery worker processes.

    This class has no support for `LAUNCHER` or `VLAUNCHER` as its strictly for local
    execution.

    The adapter handles:
    - Generation of basic shell scripts (via `LocalScriptAdapter`)
    - Local execution within worker environments (via `MerlinSubmissionMixin`)
    - Conversion of process exit codes to Merlin return codes (via `MerlinSubmissionMixin`)
    - Consistent output file handling and logging

    Usage:
        The adapter is typically instantiated by Merlin's step execution system
        and requires no special configuration beyond standard shell settings:

        >>> adapter = MerlinLocalScriptAdapter(shell="/bin/bash")
        >>> # Script generation and execution handled automatically by Merlin

    Note:
        This adapter inherits its `submit()` method from `MerlinSubmissionMixin`,
        which ensures all Merlin adapters use consistent local execution regardless
        of the script type they generate. The `LocalScriptAdapter` parent class
        is used solely for its script generation capabilities.

    Example:
        Scripts generated by this adapter are simple shell scripts:

        ```bash
        #!/bin/bash

        echo "Running workflow step"
        python my_analysis.py --input data.csv
        ```

        These scripts are executed locally using the same process as all other
        Merlin adapters, with return codes converted to Merlin's enum system
        for consistent workflow management.
    """
